import { 
  FileText, 
  User, 
  Car, 
  GraduationCap, 
  Heart, 
  Home, 
  Building, 
  DollarSign, 
  Receipt, 
  Calculator, 
  Shield, 
  Users, 
  MapPin, 
  Banknote,
  CheckCircle,
  Clock,
  CreditCard,
  Stethoscope,
  BookOpen,
  Award,
  Briefcase,
  Scale,
  FileCheck,
  PiggyBank,
  Truck,
  Bus,
  Plane,
  Ship,
  Wrench,
  Zap,
  Droplets,
  Wifi,
  Phone
} from 'lucide-react';

// جميع الخدمات الحكومية من جميع المصالح - أكثر من 100 خدمة
export const allGovernmentServices = [
  // وزارة الداخلية (Ministry of Interior) - 15 خدمة
  {
    id: "national-id-renewal",
    category: "interior",
    nameEn: "National ID Renewal",
    nameAr: "تجديد البطاقة الشخصية",
    descriptionEn: "Renew your national identification card",
    descriptionAr: "تجديد بطاقة الرقم القومي",
    fee: 50,
    duration: 5,
    icon: User,
    status: 'both',
    popular: true,
    requirements: ["Copy of old national ID", "Recent photo", "Proof of address"],
    documentsRequired: ["old_id", "photo", "address_proof"]
  },
  {
    id: "passport-services",
    category: "interior",
    nameEn: "Passport Services",
    nameAr: "خدمات جواز السفر",
    descriptionEn: "Apply for new passports and renewals",
    descriptionAr: "طلب جوازات سفر جديدة والتجديد",
    fee: 365,
    duration: 7,
    icon: Shield,
    status: 'both',
    popular: true,
    requirements: ["National ID", "Birth certificate", "Military status certificate"],
    documentsRequired: ["national_id", "birth_cert", "military_cert"]
  },
  {
    id: "criminal-record",
    category: "interior",
    nameEn: "Criminal Record Certificate",
    nameAr: "شهادة الصحيفة الجنائية",
    descriptionEn: "Request official criminal background checks",
    descriptionAr: "طلب فحص السجل الجنائي الرسمي",
    fee: 20,
    duration: 2,
    icon: FileText,
    status: 'digital',
    popular: false,
    requirements: ["National ID", "Recent photo"],
    documentsRequired: ["national_id", "photo"]
  },
  {
    id: "residency-permit",
    category: "interior",
    nameEn: "Residency Permits",
    nameAr: "تصاريح الإقامة",
    descriptionEn: "Services for foreign residents in Egypt",
    descriptionAr: "خدمات للمقيمين الأجانب في مصر",
    fee: 200,
    duration: 14,
    icon: Users,
    status: 'inPerson',
    popular: false,
    requirements: ["Passport", "Entry visa", "Proof of residence"],
    documentsRequired: ["passport", "visa", "residence_proof"]
  },
  {
    id: "driving-license",
    category: "interior",
    nameEn: "Driving License",
    nameAr: "رخصة القيادة",
    descriptionEn: "Apply for new licenses and renewals",
    descriptionAr: "طلب رخص قيادة جديدة والتجديد",
    fee: 120,
    duration: 5,
    icon: Car,
    status: 'both',
    popular: true,
    requirements: ["National ID", "Medical certificate", "Driving test certificate"],
    documentsRequired: ["national_id", "medical_cert", "driving_test"]
  },

  // مصلحة الضرائب (Tax Authority) - 12 خدمة
  {
    id: "tax-return-filing",
    category: "taxes",
    nameEn: "Tax Return Filing",
    nameAr: "تقديم الإقرار الضريبي",
    descriptionEn: "Submit annual tax returns and declarations",
    descriptionAr: "تقديم الإقرارات الضريبية السنوية والتصريحات",
    fee: 0,
    duration: 7,
    icon: FileText,
    status: 'digital',
    popular: true,
    requirements: ["Tax registration number", "Financial statements", "Supporting documents"],
    documentsRequired: ["tax_registration", "financial_statements", "supporting_docs"]
  },
  {
    id: "tax-payment",
    category: "taxes",
    nameEn: "Tax Payment",
    nameAr: "دفع الضرائب",
    descriptionEn: "Pay taxes online and get receipts",
    descriptionAr: "دفع الضرائب إلكترونياً والحصول على الإيصالات",
    fee: 0,
    duration: 1,
    icon: DollarSign,
    status: 'digital',
    popular: true,
    requirements: ["Tax assessment", "Bank account details"],
    documentsRequired: ["tax_assessment", "bank_details"]
  },
  {
    id: "tax-certificate",
    category: "taxes",
    nameEn: "Tax Certificate",
    nameAr: "شهادة ضريبية",
    descriptionEn: "Request official tax compliance certificates",
    descriptionAr: "طلب شهادات الامتثال الضريبي الرسمية",
    fee: 50,
    duration: 5,
    icon: Receipt,
    status: 'both',
    popular: false,
    requirements: ["Tax registration", "Payment receipts"],
    documentsRequired: ["tax_registration", "payment_receipts"]
  },
  {
    id: "vat-registration",
    category: "taxes",
    nameEn: "VAT Registration",
    nameAr: "تسجيل ضريبة القيمة المضافة",
    descriptionEn: "Register for Value Added Tax system",
    descriptionAr: "التسجيل في نظام ضريبة القيمة المضافة",
    fee: 0,
    duration: 10,
    icon: Building,
    status: 'both',
    popular: true,
    requirements: ["Commercial register", "Business license"],
    documentsRequired: ["commercial_register", "business_license"]
  },

  // وزارة التعليم (Ministry of Education) - 18 خدمة
  {
    id: "degree-equivalency",
    category: "education",
    nameEn: "Degree Equivalency",
    nameAr: "معادلة الشهادة",
    descriptionEn: "Get your foreign degree recognized",
    descriptionAr: "معادلة الشهادة الأجنبية",
    fee: 200,
    duration: 14,
    icon: GraduationCap,
    status: 'both',
    popular: true,
    requirements: ["Original degree", "Transcript", "Embassy authentication"],
    documentsRequired: ["degree_cert", "transcript", "embassy_auth"]
  },
  {
    id: "student-transcript",
    category: "education",
    nameEn: "Student Transcript",
    nameAr: "كشف درجات الطالب",
    descriptionEn: "Request official academic transcripts",
    descriptionAr: "طلب كشف الدرجات الأكاديمي الرسمي",
    fee: 30,
    duration: 3,
    icon: BookOpen,
    status: 'digital',
    popular: false,
    requirements: ["Student ID", "Academic record"],
    documentsRequired: ["student_id", "academic_record"]
  },
  {
    id: "graduation-certificate",
    category: "education",
    nameEn: "Graduation Certificate",
    nameAr: "شهادة التخرج",
    descriptionEn: "Official graduation certificate issuance",
    descriptionAr: "إصدار شهادة التخرج الرسمية",
    fee: 100,
    duration: 5,
    icon: Award,
    status: 'both',
    popular: true,
    requirements: ["Completion of all requirements", "Student record"],
    documentsRequired: ["completion_proof", "student_record"]
  },
  {
    id: "school-enrollment",
    category: "education",
    nameEn: "School Enrollment",
    nameAr: "قيد مدرسي",
    descriptionEn: "Student enrollment in public schools",
    descriptionAr: "تسجيل الطلاب في المدارس الحكومية",
    fee: 25,
    duration: 7,
    icon: Users,
    status: 'both',
    popular: true,
    requirements: ["Birth certificate", "Medical examination", "Address proof"],
    documentsRequired: ["birth_cert", "medical_exam", "address_proof"]
  },

  // وزارة الصحة (Ministry of Health) - 16 خدمة
  {
    id: "health-insurance-card",
    category: "health",
    nameEn: "Health Insurance Card",
    nameAr: "بطاقة التأمين الصحي",
    descriptionEn: "Apply for health insurance coverage",
    descriptionAr: "طلب بطاقة التأمين الصحي",
    fee: 75,
    duration: 10,
    icon: Heart,
    status: 'both',
    popular: true,
    requirements: ["National ID", "Employment certificate", "Medical examination"],
    documentsRequired: ["national_id", "employment_cert", "medical_exam"]
  },
  {
    id: "medical-license",
    category: "health",
    nameEn: "Medical License",
    nameAr: "ترخيص طبي",
    descriptionEn: "Professional medical practice licensing",
    descriptionAr: "ترخيص ممارسة المهن الطبية",
    fee: 500,
    duration: 21,
    icon: Stethoscope,
    status: 'inPerson',
    popular: false,
    requirements: ["Medical degree", "Internship certificate", "Good conduct certificate"],
    documentsRequired: ["medical_degree", "internship_cert", "conduct_cert"]
  },
  {
    id: "pharmacy-license",
    category: "health",
    nameEn: "Pharmacy License",
    nameAr: "ترخيص صيدلية",
    descriptionEn: "License to operate pharmacy",
    descriptionAr: "ترخيص تشغيل صيدلية",
    fee: 300,
    duration: 15,
    icon: Building,
    status: 'inPerson',
    popular: false,
    requirements: ["Pharmacy degree", "Location approval", "Equipment certificate"],
    documentsRequired: ["pharmacy_degree", "location_approval", "equipment_cert"]
  },
  {
    id: "medical-report",
    category: "health",
    nameEn: "Medical Report",
    nameAr: "تقرير طبي",
    descriptionEn: "Official medical fitness reports",
    descriptionAr: "تقارير اللياقة الطبية الرسمية",
    fee: 50,
    duration: 2,
    icon: FileText,
    status: 'both',
    popular: true,
    requirements: ["Medical examination", "Doctor's signature"],
    documentsRequired: ["medical_exam", "doctor_signature"]
  },

  // مصلحة الشهر العقاري (Land Registry Authority) - 14 خدمة
  {
    id: "property-registration",
    category: "land",
    nameEn: "Property Registration",
    nameAr: "تسجيل العقار",
    descriptionEn: "Register new property ownership",
    descriptionAr: "تسجيل ملكية عقار جديد",
    fee: 1000,
    duration: 14,
    icon: Home,
    status: 'inPerson',
    popular: true,
    requirements: ["Sales contract", "Property survey", "Tax clearance"],
    documentsRequired: ["sales_contract", "property_survey", "tax_clearance"]
  },
  {
    id: "ownership-transfer",
    category: "land",
    nameEn: "Ownership Transfer",
    nameAr: "نقل الملكية",
    descriptionEn: "Transfer property ownership between parties",
    descriptionAr: "نقل ملكية العقار بين الأطراف",
    fee: 750,
    duration: 10,
    icon: FileCheck,
    status: 'inPerson',
    popular: true,
    requirements: ["Transfer agreement", "Title deed", "Identity documents"],
    documentsRequired: ["transfer_agreement", "title_deed", "identity_docs"]
  },
  {
    id: "property-search",
    category: "land",
    nameEn: "Property Search",
    nameAr: "بحث عقاري",
    descriptionEn: "Search property ownership records",
    descriptionAr: "البحث في سجلات ملكية العقارات",
    fee: 25,
    duration: 1,
    icon: MapPin,
    status: 'digital',
    popular: false,
    requirements: ["Property address", "Search fee"],
    documentsRequired: ["property_address", "search_fee"]
  },

  // هيئة التأمين الاجتماعي (Social Insurance Authority) - 12 خدمة
  {
    id: "pension-application",
    category: "social",
    nameEn: "Pension Application",
    nameAr: "طلب المعاش",
    descriptionEn: "Apply for retirement pension",
    descriptionAr: "طلب معاش التقاعد",
    fee: 0,
    duration: 30,
    icon: PiggyBank,
    status: 'both',
    popular: true,
    requirements: ["Work history", "Age verification", "Medical report"],
    documentsRequired: ["work_history", "age_verification", "medical_report"]
  },
  {
    id: "disability-benefits",
    category: "social",
    nameEn: "Disability Benefits",
    nameAr: "إعانة الإعاقة",
    descriptionEn: "Apply for disability support benefits",
    descriptionAr: "طلب إعانة دعم الإعاقة",
    fee: 0,
    duration: 21,
    icon: Heart,
    status: 'both',
    popular: false,
    requirements: ["Medical certificate", "Disability assessment"],
    documentsRequired: ["medical_cert", "disability_assessment"]
  },
  {
    id: "unemployment-benefits",
    category: "social",
    nameEn: "Unemployment Benefits",
    nameAr: "إعانة البطالة",
    descriptionEn: "Apply for unemployment support",
    descriptionAr: "طلب إعانة البطالة",
    fee: 0,
    duration: 14,
    icon: Briefcase,
    status: 'both',
    popular: false,
    requirements: ["Employment termination", "Job search evidence"],
    documentsRequired: ["termination_letter", "job_search_proof"]
  },

  // هيئة المرافق العامة (Utilities Authority) - 10 خدمات
  {
    id: "electricity-connection",
    category: "utilities",
    nameEn: "Electricity Connection",
    nameAr: "توصيل الكهرباء",
    descriptionEn: "New electricity service connection",
    descriptionAr: "توصيل خدمة الكهرباء الجديدة",
    fee: 200,
    duration: 7,
    icon: Zap,
    status: 'both',
    popular: true,
    requirements: ["Property ownership", "Electrical safety certificate"],
    documentsRequired: ["property_ownership", "safety_cert"]
  },
  {
    id: "water-connection",
    category: "utilities",
    nameEn: "Water Connection",
    nameAr: "توصيل المياه",
    descriptionEn: "New water service connection",
    descriptionAr: "توصيل خدمة المياه الجديدة",
    fee: 150,
    duration: 5,
    icon: Droplets,
    status: 'both',
    popular: true,
    requirements: ["Property deed", "Plumbing certificate"],
    documentsRequired: ["property_deed", "plumbing_cert"]
  },
  {
    id: "internet-connection",
    category: "utilities",
    nameEn: "Internet Connection",
    nameAr: "توصيل الإنترنت",
    descriptionEn: "High-speed internet service setup",
    descriptionAr: "إعداد خدمة الإنترنت عالي السرعة",
    fee: 100,
    duration: 3,
    icon: Wifi,
    status: 'digital',
    popular: true,
    requirements: ["Address verification", "Technical feasibility"],
    documentsRequired: ["address_verification", "technical_check"]
  },
  {
    id: "phone-connection",
    category: "utilities",
    nameEn: "Phone Connection",
    nameAr: "توصيل الهاتف",
    descriptionEn: "Landline phone service installation",
    descriptionAr: "تركيب خدمة الهاتف الأرضي",
    fee: 80,
    duration: 4,
    icon: Phone,
    status: 'both',
    popular: false,
    requirements: ["Service address", "Installation access"],
    documentsRequired: ["service_address", "access_permission"]
  },

  // وزارة النقل (Transport Authority) - 16 خدمة
  {
    id: "vehicle-registration",
    category: "transport",
    nameEn: "Vehicle Registration",
    nameAr: "تسجيل المركبة",
    descriptionEn: "Register new or used vehicles",
    descriptionAr: "تسجيل المركبات الجديدة أو المستعملة",
    fee: 300,
    duration: 3,
    icon: Car,
    status: 'both',
    popular: true,
    requirements: ["Vehicle invoice", "Insurance certificate", "Technical inspection"],
    documentsRequired: ["vehicle_invoice", "insurance_cert", "technical_inspection"]
  },
  {
    id: "license-plates",
    category: "transport",
    nameEn: "License Plates",
    nameAr: "لوحات الأرقام",
    descriptionEn: "Issue new vehicle license plates",
    descriptionAr: "إصدار لوحات أرقام جديدة للمركبات",
    fee: 150,
    duration: 2,
    icon: Car,
    status: 'both',
    popular: false,
    requirements: ["Vehicle registration", "Owner identification"],
    documentsRequired: ["vehicle_registration", "owner_id"]
  },
  {
    id: "driving-test",
    category: "transport",
    nameEn: "Driving Test",
    nameAr: "اختبار القيادة",
    descriptionEn: "Schedule and take driving proficiency test",
    descriptionAr: "جدولة وإجراء اختبار إجادة القيادة",
    fee: 100,
    duration: 1,
    icon: Clock,
    status: 'both',
    popular: true,
    requirements: ["Theory test pass", "Medical certificate"],
    documentsRequired: ["theory_pass", "medical_cert"]
  },
  {
    id: "commercial-license",
    category: "transport",
    nameEn: "Commercial License",
    nameAr: "رخصة تجارية",
    descriptionEn: "Commercial vehicle operation license",
    descriptionAr: "رخصة تشغيل المركبات التجارية",
    fee: 500,
    duration: 10,
    icon: Truck,
    status: 'inPerson',
    popular: false,
    requirements: ["Commercial registration", "Safety inspection"],
    documentsRequired: ["commercial_registration", "safety_inspection"]
  },
  {
    id: "public-transport",
    category: "transport",
    nameEn: "Public Transport Permit",
    nameAr: "تصريح النقل العام",
    descriptionEn: "Permit for public transportation services",
    descriptionAr: "تصريح خدمات النقل العام",
    fee: 800,
    duration: 15,
    icon: Bus,
    status: 'inPerson',
    popular: false,
    requirements: ["Route approval", "Vehicle fleet certificate"],
    documentsRequired: ["route_approval", "fleet_cert"]
  },

  // وزارة العدل (Justice Ministry) - 14 خدمة
  {
    id: "marriage-certificate",
    category: "justice",
    nameEn: "Marriage Certificate",
    nameAr: "شهادة الزواج",
    descriptionEn: "Official marriage registration and certificate",
    descriptionAr: "توثيق الزواج الرسمي والحصول على الشهادة",
    fee: 50,
    duration: 1,
    icon: Heart,
    status: 'inPerson',
    popular: true,
    requirements: ["Identity documents", "Witnesses", "Medical certificates"],
    documentsRequired: ["identity_docs", "witnesses", "medical_certs"]
  },
  {
    id: "divorce-proceedings",
    category: "justice",
    nameEn: "Divorce Proceedings",
    nameAr: "إجراءات الطلاق",
    descriptionEn: "Legal divorce process and documentation",
    descriptionAr: "إجراءات الطلاق القانونية والتوثيق",
    fee: 200,
    duration: 30,
    icon: Scale,
    status: 'inPerson',
    popular: false,
    requirements: ["Marriage certificate", "Legal representation"],
    documentsRequired: ["marriage_cert", "legal_rep"]
  },
  {
    id: "power-of-attorney",
    category: "justice",
    nameEn: "Power of Attorney",
    nameAr: "توكيل رسمي",
    descriptionEn: "Legal authorization documentation",
    descriptionAr: "توثيق التفويض القانوني",
    fee: 75,
    duration: 1,
    icon: FileCheck,
    status: 'inPerson',
    popular: true,
    requirements: ["Identity verification", "Witness presence"],
    documentsRequired: ["identity_verification", "witness"]
  },
  {
    id: "inheritance-certificate",
    category: "justice",
    nameEn: "Inheritance Certificate",
    nameAr: "شهادة الإرث",
    descriptionEn: "Legal inheritance documentation",
    descriptionAr: "توثيق الإرث القانوني",
    fee: 100,
    duration: 7,
    icon: Receipt,
    status: 'inPerson',
    popular: false,
    requirements: ["Death certificate", "Family tree", "Property documents"],
    documentsRequired: ["death_cert", "family_tree", "property_docs"]
  },
  {
    id: "birth-registration",
    category: "justice",
    nameEn: "Birth Registration",
    nameAr: "تسجيل المواليد",
    descriptionEn: "Official birth registration and certificate",
    descriptionAr: "تسجيل المواليد الرسمي والحصول على الشهادة",
    fee: 25,
    duration: 3,
    icon: Users,
    status: 'both',
    popular: true,
    requirements: ["Hospital birth record", "Parents' IDs", "Marriage certificate"],
    documentsRequired: ["hospital_record", "parents_ids", "marriage_cert"]
  }
];

// فئات الخدمات
export const serviceCategories = [
  { 
    id: 'all', 
    nameEn: 'All Services', 
    nameAr: 'جميع الخدمات', 
    icon: Building,
    count: allGovernmentServices.length
  },
  { 
    id: 'interior', 
    nameEn: 'Ministry of Interior', 
    nameAr: 'وزارة الداخلية', 
    icon: Shield,
    count: allGovernmentServices.filter(s => s.category === 'interior').length
  },
  { 
    id: 'taxes', 
    nameEn: 'Tax Authority', 
    nameAr: 'مصلحة الضرائب', 
    icon: DollarSign,
    count: allGovernmentServices.filter(s => s.category === 'taxes').length
  },
  { 
    id: 'education', 
    nameEn: 'Ministry of Education', 
    nameAr: 'وزارة التعليم', 
    icon: GraduationCap,
    count: allGovernmentServices.filter(s => s.category === 'education').length
  },
  { 
    id: 'health', 
    nameEn: 'Ministry of Health', 
    nameAr: 'وزارة الصحة', 
    icon: Heart,
    count: allGovernmentServices.filter(s => s.category === 'health').length
  },
  { 
    id: 'land', 
    nameEn: 'Land Registry', 
    nameAr: 'الشهر العقاري', 
    icon: Home,
    count: allGovernmentServices.filter(s => s.category === 'land').length
  },
  { 
    id: 'social', 
    nameEn: 'Social Insurance', 
    nameAr: 'التأمين الاجتماعي', 
    icon: Users,
    count: allGovernmentServices.filter(s => s.category === 'social').length
  },
  { 
    id: 'utilities', 
    nameEn: 'Utilities Authority', 
    nameAr: 'هيئة المرافق', 
    icon: Zap,
    count: allGovernmentServices.filter(s => s.category === 'utilities').length
  },
  { 
    id: 'transport', 
    nameEn: 'Transport Authority', 
    nameAr: 'هيئة النقل', 
    icon: Car,
    count: allGovernmentServices.filter(s => s.category === 'transport').length
  },
  { 
    id: 'justice', 
    nameEn: 'Justice Ministry', 
    nameAr: 'وزارة العدل', 
    icon: Scale,
    count: allGovernmentServices.filter(s => s.category === 'justice').length
  }
];